speech_to_text_model:
  whisper_model_name: "openai/whisper-large-v3"

speaker_enrichment:
  # models for identifying speakers' gender
  audio_model_name: "alefiury/wav2vec2-large-xlsr-53-gender-recognition-librispeech"
  image_model_name: "IDEA-Research/grounding-dino-base"
  siglip_model_name: "google/siglip-so400m-patch14-384"
  siglip_processor: "google/siglip-so400m-patch14-384"

  voting_weights:  # weights to give each of the approaches when combining results
    audio: 0.0   # by audio
    image: 0.0   # by image (screenshot)
    text: 0.0    # by text (transcript analysis with UDPipe)

llm_transcriber:
  model_name: "gemini-2.5-flash"  # this model will be used for creating transcripts
  chunk_length_in_min: 8 # length of audio chunks to be sent to the LLM transcriber
  overlap_in_min: 1    # overlap between audio chunks to avoid cutting sentences
  api_keys_config:
    env_variables_names:
      - "GEMINI_API_KEY_1"
      - "GEMINI_API_KEY_2"
      - "GEMINI_API_KEY_3"
      - "GEMINI_API_KEY_4"
      - "GEMINI_API_KEY_5"
      - "GEMINI_API_KEY_6"
      - "GEMINI_API_KEY_7"
      - "GEMINI_API_KEY_8"
      - "GEMINI_API_KEY_9"
      - "GEMINI_API_KEY_10"
      - "GEMINI_API_KEY_11"
      - "GEMINI_API_KEY_12"
      - "GEMINI_API_KEY_13"
      - "GEMINI_API_KEY_14"
      - "GEMINI_API_KEY_15"
      - "GEMINI_API_KEY_16"
      - "GEMINI_API_KEY_17"
      - "GEMINI_API_KEY_18"
      - "GEMINI_API_KEY_19"
      - "GEMINI_API_KEY_20"