storage:
  upload_dir: "data/uploads"
  working_files_dir: "data/working_files"

hugging_face_token_name: "HUGGING_FACE_TOKEN"  # for accessing Hugging Face models (e.g. pyannote)
diarization_model_name: "pyannote/speaker-diarization-3.1"

speech_to_text_model:
  whisper_model_name: "openai/whisper-large-v3"
  target_language: "uk"

speaker_enrichment:
  # models for identifying speakers' gender
  audio_model_name: "prithivMLmods/Common-Voice-Geneder-Detection"
  image_model_name: "IDEA-Research/grounding-dino-base"
