from src.utils.segment import Segment
from conllu import TokenList


class NlpAligner:
    """
    Responsible for mapping UDPipe output back to time-coded Segments.
    """

    def align(self, segments: list[Segment], nlp_sentences: list[TokenList]) -> list[Segment]:
        """
        Aligns linear NLP sentence data with time-coded speech segments.

        Args:
            segments (list[Segment]): An ordered list of transcript segments containing
                                      raw speech and timestamps.
            nlp_sentences (list[TokenList]): An ordered list of parsed sentences (conllu objects) generated by UDPipe
            from the full transcript text.

        Returns:
            list[Segment]: The list of segments, enriched with NLP data in `segment.nlp_data`.
        """
        count = 0
        total_udpipe_sentences = len(nlp_sentences)

        for segment in segments:
            segment.nlp_data = []
            # normalize speech
            remaining_segment_text = segment.speech.replace("\n", "").strip()
            while remaining_segment_text and count < total_udpipe_sentences:
                current_nlp_sentence = nlp_sentences[count]
                udpipe_text = current_nlp_sentence.metadata.get("text", "").strip()

                if remaining_segment_text.startswith(udpipe_text):
                    segment.nlp_data.append(current_nlp_sentence)
                    remaining_segment_text = remaining_segment_text[len(udpipe_text):].strip()

                    count += 1
                else:
                    print(f"WARNING: text is not matching!")
                    break

        return segments
